### PR TITLE
Preserve scroll directive

### PR DESCRIPTION
**Pull request by pascalbaljet**

### CODE REVIEW

**Comment by JapSeyz** [comment]
How is this to be used?

Reading the code, I believed it'd be either:

- `preserve-scroll`
- `@preserveScroll("keyword")`

However the first option does nothing at all, and the second option throws:

`TypeError: undefined is not an object (evaluating 'dir.deep')`

image

**Comment by pascalbaljet** [comment]
I haven't documented it yet, but did you update the JS package as well? Your code is right. Here's an example from the test suite:

```blade
<div>
    <div @preserveScroll('sidebar') class="w-[16rem] absolute top-0 left-0 max-h-screen h-full overflow-y-scroll">
        {{-- scrolling menu --}}
    </div>

    <div class="pl-[16rem]">
        {{-- content --}}
    </div>
</div>
```

**Comment by iMusicJJ** [comment]
> but did you update the JS package as well

Yes, but it may be that the NPM registry hadn't updated yet. I'll try again later today

**Comment by JapSeyz** [comment]
> but did you update the JS package as well

Yes, but it may be that the NPM registry hadn't updated yet. I'll try again later today

**Pull request merged**
