### PR TITLE
fix: Automatic Installation doesn't work well on windows OS

### PR DESCRIPTION
**Pull request by sidiqaldi**
fix  Automatic Installation doesn't work well on windows OS

### CODE REVIEW

**Comment by pascalbaljet** [comment]
I see that it works, but I don't fully understand why. `PHP_EOL` is supposed to be OS independent, right?

**Comment by pascalbaljet** [comment]
@sidiqaldi Thanks for helping!

**Comment by sidiqaldi** [comment]
Windows support both EOL with `\r` and `\n` so it thinks it's ok to force using `\n` like in unix based.

https://stackoverflow.com/questions/128560/when-do-i-use-the-php-constant-php-eol

**Comment by Rattone** [comment]
I don't understand why PHP_EOL doesn't already do what it's meant to do. Do you have an explanation?

**Pull request merged**
