### PR TITLE
Automatically add a red star to the label when a field is marked as required

### PR DESCRIPTION
**Pull request by J87NL**
As requested in the Splade Discord so we are able to do:

```
->label(__('Title <span class="text-red-500">*</span>'))
```

### CODE REVIEW

**Comment by J87NL** [comment]
Could be a nice idea to automatically add a red star to the label when a field is marked as required, I'm working on this.

**Comment by AliasSuperman** [comment]
I achieved it like this: in form.label.blade.php

`<span class="mb-1 block font-sans text-gray-700">
    {{ $label }}@if ($attributes->has('required'))
        <span class="text-red-500">*</span>
    @endif
</span>
`

**Comment by J87NL** [comment]
@AliasSuperman just added this approach, had to add `required` to the `attributes` for this.
I'm not entirely convinced this HTML5-validation is the desired way to go because you now get the 'Please fill in this field' when trying to submit instead of the formvalidation message below the field after submitting. It feels a bit like not using the power/charms of Splade, what do you think @pascalbaljet?

**Comment by pascalbaljet** [comment]
I'm not a fan of the default HTML5 validation capabilities. I would suggest adding `htmlLabel` and `htmlHelp` methods, and allow passing a `HtmlString` to the `label` and `help` methods:

```php
Input::make('hiddenInput2')
    ->htmlLabel('Title <span class="text-red-500">*</span>');

// which will be a shortcut to:

Input::make('hiddenInput2')
    ->label(new HtmlString('Title <span class="text-red-500">*</span>'));
```

https://github.com/protonemedia/laravel-splade/pull/378

**Comment by MdAnowarHosen** [comment]
Good idea!

**Comment by pascalbaljet** [comment]
@J87NL Can this PR be closed now that we have `htmlLabel()`?

**Comment by J87NL** [comment]
Preferably not, this PR adds the red asterisks automatically to all FormBuilder Splade-fields that have a required rule, so without the need of adding extra htmlLabels to all fields where you want the red asterisk.

I've added a config variable to enable/disable the asterisks.

**Comment by pascalbaljet** [comment]
Must admit it's quite nice! One more question: what the reason behind using `data-required` in the Form Builder instead of the `required` attribute?

**Comment by J87NL** [comment]
Just 'required' would make it HTML5-validation which would prevent the form from being able to submit, and therefore you won't see the formrequest validation.

**Pull request merged**
