### PR TITLE
Support Dark Mode & RTL Support

### PR DESCRIPTION
**Pull request by 3x1io**
add Arabic lang files to the app

### CODE REVIEW

**Comment by 3x1io** [comment]
## What i do?

- add new lang [Arabic] to the lang path
- build a dark theme using `dark class` on tailwindcss 
- build a RTL theme using `tailwindcss-rtl` package
- fix RTL problems
- fix Dark problems 

## Screenshots

<a href="https://imgbb.com/">Screenshot-2023-01-04-at-12-35-19-PM</a>
<a href="https://ibb.co/mN8YPpX">Screenshot-2023-01-04-at-12-35-43-PM</a>
<a href="https://ibb.co/98Z7wsF">Screenshot-2023-01-04-at-12-35-52-PM</a>
<a href="https://ibb.co/H7v6W9T">Screenshot-2023-01-04-at-12-36-06-PM</a>
<a href="https://imgbb.com/">Screenshot-2023-01-04-at-12-36-12-PM</a>
<a href="https://imgbb.com/">Screenshot-2023-01-04-at-12-36-19-PM</a>
<a href="https://imgbb.com/">Screenshot-2023-01-04-at-12-36-23-PM</a>

**Comment by pascalbaljet** [comment]
Hey @3x1io, thanks for the PR! Could you remove the Arabic translation files from the PR?

**Comment by 3x1io** [comment]
oky i will make it on another pr

**Review by YasinAshorian — APPROVED** [review]

**Comment by pascalbaljet** [comment]
Thanks! I've added a new folder with the Splade translation files:
https://github.com/protonemedia/laravel-splade/tree/main/resources/lang

**Comment by 3x1io** [comment]
#143 #169 
i think i fix those.

**Pull request closed without merging**
