### PR TITLE
Fix problems reported by PHPStan

### PR DESCRIPTION
**Pull request by szepeviktor**
`vendor/bin/phpstan analyze -c vendor/nunomaduro/larastan/extension.neon -l 5 src/` 🤩

### CODE REVIEW

**Comment by szepeviktor** [comment]
You may be interested in https://github.com/phpstan/phpstan/issues/7675

**Comment by pascalbaljet** [comment]
Thanks again! I’ll add Larastan as a GitHub Action.

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
Good news @pascalbaljet!
The above bug is fixed in PHPStan.

So the next release will not produce this false positive 🎉

**Pull request merged**
