### PR TITLE
Terminate Splade request

### LINKED ISSUE #151: Toasts firing multiple times on Octane
Hey,

It seems there's some kind of disconnect with [Laravel Octane](https://laravel.com/docs/9.x/octane).

Hitting a route with the following code:

```php
\Log::info('House ProfileImagesRequest');
Toast::title(__('Images updated successfully.'));

return redirect()->back();
```

Upon being redirected back, 2 identical toasts show up, and upon a page-reload 6 identical toasts show up.

It seems they are continuously being read from [SpladeCore::$toasts](https://github.com/protonemedia/laravel-splade/blob/main/src/SpladeCore.php#L39) and added to the session, but SpladeCore::$toasts is not being reset, so more and more toasts are just being added.

Adding a [terminable middleware](https://laravel.com/docs/9.x/middleware#terminable-middleware) seems to fix the issue (and any memory leaks)

```php
public function terminate($request, $response)
{
    $this->splade->reset();
}
```

I'll create a PR for this

### PR DESCRIPTION
**Pull request by JapSeyz**
Fixes #151

### CODE REVIEW

**Comment by JapSeyz** [comment]
Oh, unfortunately this only fixes the addition of new toasts. I am still unable to remove toasts again

**Comment by JapSeyz** [comment]
Ah, `SpladeCore->reset()` is bugged. `$this->modalKey = null;` is just throwing exceptions, because modalKey cannot be null.

**Comment by JapSeyz** [comment]
Fixing `->reset()` seems to fix the problem entirely

**Comment by pascalbaljet** [comment]
> Edit: [Larastan](https://github.com/nunomaduro/larastan) would find a problem like this in the future.
> 
> I can setup a CI action for static checking, if you want?

That would be great, thanks!

**Comment by JapSeyz** [comment]
> That would be great, thanks!

Great! Now there is a CI for it, however it fails due to ~600 issues on max level, and ~170 on level 5.

The easy way is to generate a baseline for it now, and just prevent any new issues. Let me know if that's the way you want to go, and I'll generate a baseline for it

**Comment by pascalbaljet** [comment]
I think level 5 with a baseline is fine for now.

**Comment by JapSeyz** [comment]
Hi, so because of the breaking changes between 8.1 and 8.2 ; I cannot create a baseline that works for both 8.1 and 8.2.

For now I've disabled the 8.2 check, but you could look into fixing those 17 issues, and enable the 8.2 check again :)

**Comment by pascalbaljet** [comment]
Closed in favor of #195

**Pull request closed without merging**
