### PR TITLE
add some toast method in the toast controller and add also correspond…

### PR DESCRIPTION
**Pull request by Donald1597**
…ing routes

### CODE REVIEW

**Comment by pascalbaljet** [comment]
Hey! The `app` folder is only used for internal Dusk testing. Any reason you added the routes?

**Comment by Donald1597** [comment]
@pascalbaljet  For my part when I was testing the toast functionalities I wanted to see everything but there were only a few methods available so I thought it useful to add the missing methods and routes to allow others to test a lot more precise and therefore a better grip of the toast.

**Comment by Donald1597** [comment]
> Hey! The `app` folder is only used for internal Dusk testing. Any reason you added the routes?

For my part when I was testing the toast functionalities I wanted to see everything but there were only a few methods available so I thought it useful to add the missing methods and routes to allow others to test a lot more precise and therefore a better grip of the toast.

**Comment by pascalbaljet** [comment]
Got it! I'm not going to merge it as users can do the same in their own demo projects 👍

**Pull request closed without merging**
